version: '3'
services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    ports:
      - 80:80
    volumes:
      - .:/var/www/html
    links:
      - bancodedados
  bancodedados:
    image: mariadb:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: apresentacao
      MYSQL_USER: caio
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: 123456
